config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users

  resource :charity
  get 'dashboard' => 'charities#show', as: :dashboard
  
  resources :auctions
  post 'auctions/wrapup' => 'auctions#wrapup', as: :wrapup
  post 'confirm_payment' => 'payment_notifications#confirm_payment'

  resources :items do
    resources :bids, only: :create
    resources :watch_list_items, only: :create
  end
  resources :watch_list_items, only: [:index, :update, :destroy]

  get 'my_donations' => 'items#show_my_donations', as: :my_donations
  get 'review' => 'items#review' 

end

app/models/charity.rb
class Charity < ActiveRecord::Base

  validates :name, :url, :bg_color, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sesitive: false }

  has_many :auctions, inverse_of: :charity
  has_attached_file :logo, 
  :styles => { :medium => "300x300>", :thumb => "200x200>", :tiny => "100x100>" }, 
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :require_admin, only: :show
  
  def new
    if Charity.any?
      flash[:alert] = "Charity setup already completed"
      redirect_to and return root_url
    else    
      @charity = Charity.new
      render :layout => false
    end
  end
  
  def create
    @charity = Charity.new(charity_params)
    if @charity.save
      redirect_to new_user_registration_path
    else
      render 'new', :layout => false
    end
  end
  
  # Charities#show corresponds to the sponsor dashboard.
  def show
    @auctions = Auction.order(finish: :desc)
    unless @current_auction.nil?
      @pending_items_count = @current_auction.items.where(approved: false, declined: false).count
    else
      @pending_items_count = 0
    end
  end
  
  def edit
    @charity = Charity.last
  end
  
  def update
    @charity = Charity.last
    if @charity.update(charity_params)
      flash[:notice] = "Your Charity's information has been updated!"
      redirect_to dashboard_path
    else
      render 'edit'
    end
  end
  
  private
  
  def charity_params
    params.require(:charity).permit(:name, :subhead, :email, :url, :logo, :bg_color)
  end

end

app/views/charities/_form.html.erb
<%= form_for @charity, url: charity_path(@charity) do |f| %>

  <% if @charity.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@charity.errors.count, "error") %>.
    </div>
    <ul>
      <% @charity.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :name, "Charity Name:" %><br />
    </div>
    <div class="col-md-3">
      <%= f.text_field :name, class: "form-control", placeholder: "Charity Name"  %>
    </div>
  </div>
  
  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :subhead, "Sub-Heading (Optional):" %><br />
    </div>
    <div class="col-md-3">
      <%= f.text_field :subhead, class: "form-control", placeholder: "Example: Eastern Chapter"  %>
    </div>
  </div>
  
  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :email, "Charity Email:" %><br />
    </div>
    <div class="col-md-3">
      <%= f.email_field :email, class: "form-control", placeholder: "auction@charity.com" %>
    </div>
  </div>
  
  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :url, "Homepage:" %><br />
    </div>
    <div class="col-md-3">
      <%= f.text_field :url, class: "form-control", placeholder: "www.charity.com" %>
    </div>
  </div>
  
<div class="row form-group">
  <div class="col-md-2">
    <%= f.label :logo, 'Logo:' %>
  </div>
  <% if @charity.persisted? %>
    <div class="col-md-1">
      <%= f.label :logo, "Current:" %>
    </div>
    <div class="col-md-2">
      <%= image_tag @charity.logo.url(:tiny), class: "logo" %>
    </div>
    <div class="col-md-1">
      <%= f.label :logo, "Update:" %>
    </div>
  <% end %>
  <div class="col-md-3">
    <%= f.file_field :logo, class: 'form-control' %>
  </div>
</div>
  
  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :bg_color, "Background Color:" %><br />
    </div>
    <div class="col-md-3">
      <% bg_color = @charity.new_record? ? "#eeeeee" : @charity.bg_color %>
      <%= f.color_field :bg_color, class: "form-control", value: bg_color %>
    </div>
  </div>
  
<div class="row">
  <div class="col-md-2">
    <% button_txt = @charity.new_record? ? 'Create Charity' : 'Update Charity' %>
    <%= f.submit "#{button_txt}", class: "form-control btn btn-primary" %>
  </div>
  <% unless @charity.new_record? %>
  <div class="col-md-2">
    <%= link_to "Back", dashboard_path, class: 'btn btn-danger' %>
  </div>
  <% end %>
</div>
<% end %>

app/views/charities/edit.html.erb
<h1>Edit Charity</h1>

<%= render 'form' %>

app/views/charities/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class="container">  
  <div class="jumbotron">
    <h1>Welcome!</h1>
    <p>We need some information about your charity in order to continue.</p>
  </div>

  <%= render 'form' %>

</div>

app/views/charities/show.html.erb
<h1>Dashboard</h1>

<div class="container">
  <div class="row">
    <div class="col-md-4 panel-dashboard">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Auction Tasks</h3>
        </div>
        <div class="panel-body">
          <div class="panel-link"><%= link_to "Create Auction", new_auction_path %></div>
          <% unless @current_auction.nil? %>
          <div class="panel-link"><%= link_to "Review Donations", review_path %>
            <span class="badge"><%= @pending_items_count %></span></div>

          <div class="panel-link">
            <%= link_to "Edit Current Auction", edit_auction_path(@current_auction) %>
          </div>
          <div class="panel-link">
            <%= link_to "Cancel Current Auction", auction_path(@current_auction),
                method: :delete, data: {confirm: "WARNING: This will delete all current auction info. Are you sure?" } %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Auction Summaries</h3>
        </div>
        <div class="panel-body">
          <% if Auction.exists? %>
          <% @auctions.each do |auction| %>
          <% duration = auction.start.strftime('%m/%d') + '-' + \
                    auction.finish.strftime('%x') %>
          <div class="row">
            <div class="col-md-6">
              <%= link_to "#{auction.name}", auction_path(auction) %>
            </div>
            <div class="col-md-6">
              <%= link_to "#{duration}", auction_path(auction) %>
            </div>
          </div>
          <% end %>
          <% else %>
            No auctions available.
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Charity Details</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4">
              <div>Name:</div>
              <div>Sub-Heading:</div>
              <div>Email:</div>
              <div>Homepage:</div>
              <div>Header Color:</div>
            </div>
            <div class="col-md-8">
              <div><%= @charity.name %></div>
              <div><%= @charity.subhead %></div>
              <div><%= @charity.email %></div>
              <div><%= @charity.url %></div>
              <div class="color-box" style="background-color:<%= @charity.bg_color %>"></div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="panel-link"><%= link_to "Edit Charity", edit_charity_path %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>