config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users

  resource :charity
  get 'dashboard' => 'charities#show', as: :dashboard
  
  resources :auctions
  post 'auctions/wrapup' => 'auctions#wrapup', as: :wrapup
  post 'confirm_payment' => 'payment_notifications#confirm_payment'

  resources :items do
    resources :bids, only: :create
    resources :watch_list_items, only: :create
  end
  resources :watch_list_items, only: [:index, :update, :destroy]

  get 'my_donations' => 'items#show_my_donations', as: :my_donations
  get 'review' => 'items#review' 

end

app/models/watch_list_item.rb
class WatchListItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  
  validates :item, presence: true
  validates :user, presence: true
  
  def to_s
    item.name
  end

end

app/controllers/watch_list_items_controller.rb
class WatchListItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    watch_list_items = WatchListItem.where(user: current_user)
    items = watch_list_items.map { |watch_list_item| watch_list_item.item }
    items.keep_if { |i| i.auction == @current_auction }
    @watch_list = Hash.new
    items.each do |item|
      user_bid = item.bids.where(user: current_user).maximum("amount") || 0
      @watch_list[item] = {
                 :status => status_msg(item),
                 :user_bid => user_bid,
                 :watch_list_item => watch_list_items.find_by(item: item) }
    end   
  end

  def create
    item = Item.find(params[:item_id])
    watch_list_item = WatchListItem.new(item: item, user: current_user)
    if watch_list_item.save
      flash[:notice] = "#{item.name} added to your watch list."
    else
      flash[:alert] = "#{item.name} could not be added to your watch list."
    end
    redirect_to :back
  end

  def update
    watch_list_item = WatchListItem.find(params[:id])
    watch_list_item.toggle!(:wants_email)
    item = watch_list_item.item.name
    if watch_list_item.wants_email
      msg = "You will receive an email if you are outbid for the item: "
    else
      msg = "You will not be notified regarding the item: "
    end
    redirect_to :back, :notice => msg + item
  end

  def destroy
    watch_list_item = WatchListItem.find(params[:id])
    item = watch_list_item.item
    watch_list_item.destroy
    redirect_to :back, :notice => "#{item.name} removed from your watch list."
  end

  private
  
  def status_msg(item)
     if item.bids.where(user: current_user).empty?
        "You have not bid."
     elsif item.high_bid.user == current_user
       if item.auction.finish < DateTime.current
        "You won this item."
       else
        "You are winning this item."
       end
     else
        "You have been outbid!"
     end
  end
  
end

app/views/watch_list_items/index.html.erb
<h1>My Watchlist</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Item</th>
      <th>Current Bid</th>
      <th>My Bid</th>
      <th>Status</th>
      <th class="text-center">Email if Outbid?</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'items/no_items' if @watch_list.empty? %>
    <% @watch_list.each do |item, details| %>
    <tr>
      <% if item.photo_file_name.nil? %>
        <td><span style="font-size: 25px;" class="glyphicon glyphicon-camera"></span></td>
      <% else %>
        <td><%= link_to image_tag(item.photo.url(:thumb)), item_path(item) %></td>
      <% end %>
      <td><%= link_to item, item_path(item) %></td>
      <td>$<%= item.high_bid.try(:amount) || 0 %></td>
      <td>$<%= details[:user_bid] %></td>
      <td><%= details[:status] %></td>
      <% if details[:watch_list_item].wants_email %>
           <% symbol = ["glyphicon", "glyphicon-minus-sign"] %>
      <% else %>
           <% symbol = ["glyphicon", "glyphicon-plus-sign"] %>
      <% end %>
      <td class="text-center">
        <%= link_to watch_list_item_path(details[:watch_list_item].id),
                    method: :patch do %>
          <%= content_tag(:span, '', class: symbol) %>
        <% end %>
      </td>
      <td><%= link_to 'Remove Item',
              watch_list_item_path(details[:watch_list_item].id),
                       method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>