config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users

  resource :charity
  get 'dashboard' => 'charities#show', as: :dashboard
  
  resources :auctions
  post 'auctions/wrapup' => 'auctions#wrapup', as: :wrapup
  post 'confirm_payment' => 'payment_notifications#confirm_payment'

  resources :items do
    resources :bids, only: :create
    resources :watch_list_items, only: :create
  end
  resources :watch_list_items, only: [:index, :update, :destroy]

  get 'my_donations' => 'items#show_my_donations', as: :my_donations
  get 'review' => 'items#review' 

end

app/views/layouts/_auction_details.html.erb
<div class="row">
  <div class="col-md-5"><h1><%= @current_auction %></h1></div>
  <div class="col-md-7 h3 countdown"><%= countdown_explanation %>
    <div id="getting-started"></div>
    <%= javascript_tag do %>
    $("#getting-started")
    .countdown(<%= config_countdown %>, function(event) {
    $(this).text(
    event.strftime('%D Days %H:%M:%S')
    );
    });
    <% end %>
  </div>
</div>
<h2><%= @current_auction.duration %></h2>

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <div class='alert alert-danger'><%= alert %></div>
<% elsif flash[:notice] %>
  <div class='alert alert-success'><%= notice %></div>
<% end %>

app/views/layouts/_header.html.erb
<div class="page-header" style="background-color: <%= @charity.bg_color %>;">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag @charity.logo.url(:thumb), class: "logo" %>
    </div>
    <div class="col-md-9">
      <h2><%= @charity.name%><br>
        <small><%= @charity.subhead %></small>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="nav navbar-nav pull-right layout-nav">
        <li class=<%= 'active' if current_page?(root_path) %>>
          <%= link_to "Browse Items", root_path %>
        </li>
        <li class=<%= 'active' if current_page?(new_item_path) %>>
          <%= link_to "Donate an Item", new_item_path %>
        </li>
        <% if user_signed_in? %>
          <li class=<%= 'active' if current_page?(watch_list_items_path) %>>
            <%= link_to "My Watchlist", watch_list_items_path %>
          </li>
          <li class=<%= 'active' if current_page?(my_donations_path) %>>
            <%= link_to "My Donations", my_donations_path %>
          </li>
          <li class=<%= 'active' if current_page?(dashboard_path) %>>
            <%= link_to "Dashboard", dashboard_path if current_user.admin? %>
          </li>
          <li class=<%= 'active' if current_page?(destroy_user_session_path) %>>
            <%= link_to "Sign Out (#{current_user.to_s.titleize})",
                         destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class=<%= 'active' if current_page?(new_user_session_path) %>>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
          <li class=<%= 'active' if current_page?(new_user_registration_path) %>>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/auction_details' unless @current_auction.nil? %>

    <body>

      <%= render 'layouts/flash' %>
      <%= yield %>

    </body>
  </div>
</html>